// ═══════════════════════════════════════════════════════════════════════════════
// GupShupGo — Email Service (Nodemailer + Brevo SMTP)
// ═══════════════════════════════════════════════════════════════════════════════
// Thin wrapper around Nodemailer with connection pooling. Reads credentials
// from Firebase Secrets (defineSecret). Never throws — failures are logged
// and swallowed so email issues never crash the calling Cloud Function.
// ═══════════════════════════════════════════════════════════════════════════════

const crypto = require("crypto");
const nodemailer = require("nodemailer");
const { defineSecret } = require("firebase-functions/params");

// ─── Secrets (set via: firebase functions:secrets:set SMTP_USER / SMTP_PASS) ──
const smtpUser = defineSecret("SMTP_USER");
const smtpPass = defineSecret("SMTP_PASS");

// ─── Unsubscribe HMAC Secret ──────────────────────────────────────────────────
// Set via: firebase functions:secrets:set UNSUBSCRIBE_SECRET
const unsubscribeSecret = defineSecret("UNSUBSCRIBE_SECRET");

// ─── Transporter (lazy singleton) ──────────────────────────────────────────────
let _transporter = null;

function getTransporter() {
  if (_transporter) return _transporter;

  _transporter = nodemailer.createTransport({
    host: "smtp-relay.brevo.com",
    port: 587,
    secure: false, // STARTTLS
    auth: {
      user: smtpUser.value(),
      pass: smtpPass.value(),
    },
    pool: true,
    maxConnections: 5,
    maxMessages: 100,
    // Timeout settings to prevent hanging
    connectionTimeout: 10000,
    greetingTimeout: 10000,
    socketTimeout: 15000,
  });

  return _transporter;
}

// ─── Send Email ────────────────────────────────────────────────────────────────
/**
 * Sends a single email via Brevo SMTP. Never throws.
 *
 * @param {string} to        Recipient email address
 * @param {string} subject   Email subject line
 * @param {string} html      Full HTML email body
 * @returns {Promise<boolean>} true if sent successfully
 */
async function sendEmail(to, subject, html) {
  if (!to || !subject || !html) {
    console.warn("sendEmail: missing required field (to/subject/html), skipping");
    return false;
  }

  try {
    const transporter = getTransporter();

    const info = await transporter.sendMail({
      from: {
        name: "GupShupGo",
        address: "vansh.sethi98760@gmail.com",
      },
      to,
      subject,
      html,
      // Plain-text fallback (auto-generated by most clients, but belt-and-suspenders)
      text: subject,
      headers: {
        // Brevo tracking (optional — disable if you don't want open/click tracking)
        "X-Mailin-Tag": "gupshupgo-transactional",
      },
      // Logo is now served inline from Firebase Storage via the HTML template
      // (see email-templates.js → LOGO_URL), not as an SMTP attachment.
    });

    console.log(`Email sent to ${to}: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error(`Email to ${to} failed:`, error.message || error);
    // Reset transporter on auth/connection errors so next call retries fresh
    if (
      error.code === "EAUTH" ||
      error.code === "ECONNECTION" ||
      error.code === "ESOCKET"
    ) {
      _transporter = null;
    }
    return false;
  }
}

// ─── Batch Send ────────────────────────────────────────────────────────────────
/**
 * Sends the same email to multiple recipients (individually, not CC/BCC).
 * Returns the count of successful sends.
 *
 * @param {Array<{email: string, name: string}>} recipients
 * @param {function(name: string, email: string): {subject: string, html: string}} templateFn
 * @returns {Promise<number>} Number of successfully sent emails
 */
async function sendBatch(recipients, templateFn) {
  if (!recipients || recipients.length === 0) return 0;

  let successCount = 0;

  // Process in serial batches of 10 to respect Brevo rate limits
  const BATCH_SIZE = 10;
  for (let i = 0; i < recipients.length; i += BATCH_SIZE) {
    const batch = recipients.slice(i, i + BATCH_SIZE);
    const results = await Promise.all(
      batch.map(async (r) => {
        try {
          const { subject, html } = templateFn(r.name, r.email);
          const sent = await sendEmail(r.email, subject, html);
          if (sent) successCount++;
          return sent;
        } catch (e) {
          console.error(`Batch email to ${r.email} failed:`, e.message);
          return false;
        }
      })
    );
  }

  console.log(`sendBatch: ${successCount}/${recipients.length} emails sent`);
  return successCount;
}

// ─── Build unsubscribe URL ─────────────────────────────────────────────────────
/**
 * Generates a signed unsubscribe URL with an HMAC token so the endpoint
 * can verify the request originated from a legitimate email link.
 */
function buildUnsubscribeUrl(userId) {
  const token = crypto
    .createHmac("sha256", unsubscribeSecret.value())
    .update(userId)
    .digest("hex");
  return `https://us-central1-videocallapp-81166.cloudfunctions.net/unsubscribeEmail?uid=${encodeURIComponent(userId)}&token=${token}`;
}

// ─── Verify unsubscribe token ──────────────────────────────────────────────────
/**
 * Verifies that an HMAC token matches the expected value for a given user ID.
 * Uses timingSafeEqual to prevent timing attacks.
 */
function verifyUnsubscribeToken(userId, token) {
  if (!userId || !token) return false;
  try {
    const expected = crypto
      .createHmac("sha256", unsubscribeSecret.value())
      .update(userId)
      .digest("hex");
    if (expected.length !== token.length) return false;
    return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(token));
  } catch {
    return false;
  }
}

module.exports = {
  sendEmail,
  sendBatch,
  buildUnsubscribeUrl,
  verifyUnsubscribeToken,
  // Export secrets so Cloud Functions that use this module can declare them
  secrets: [smtpUser, smtpPass, unsubscribeSecret],
};
