import 'dart:math';

import 'package:video_chat_app/models/message_model.dart';

/// Pure helpers shared by [MeshNetworkService] and its callers.
///
/// They live outside `mesh_network_service.dart` on purpose: that file pulls in
/// `nearby_connections`, `firebase_storage` and `device_info_plus`, and these
/// three functions are the part of the mesh file path that is worth unit
/// testing. Keeping them plugin-free means the test is a plain Dart test.

/// Largest document a mesh send will carry, in bytes (25 MB).
///
/// Sized to match [kMaxMeshVideoBytes] rather than the 64 MB online document cap
/// (`_kMaxChatVideoBytes` in chat_screen.dart), for the same reason the video
/// ceiling is tighter: a mesh transfer streams peer-to-peer over the `FILE`
/// channel with no progress reporting and no resume, so a file big enough to
/// take minutes is a file the user watches fail silently.
const int kMaxMeshDocumentBytes = 25 * 1024 * 1024;

/// Longest filename allowed onto the wire.
///
/// The `file_metadata` BYTES packet is capped at ~32 KB by Nearby and overflows
/// silently. A document's message JSON carries no base64 poster, so the filename
/// is the only field a peer controls that could get anywhere near that — clamp
/// it rather than let it be the thing that breaks the send.
const int kMaxMeshFileNameChars = 200;

/// Where a received mesh file of [type] belongs on disk.
///
/// Every received file used to land in `mesh_images/` regardless of type, which
/// was survivable while the directory was only ever a container — but it put
/// voice notes and video in the photos folder, and a document would have joined
/// them. The sender-side copies already use these four names.
String meshDirNameForType(MessageType type) => switch (type) {
      MessageType.audio => 'mesh_audio',
      MessageType.video => 'mesh_videos',
      MessageType.document => 'mesh_documents',
      _ => 'mesh_images',
    };

/// Make a wire-supplied filename safe to interpolate into a local path.
///
/// The name in a `file_metadata` packet is generated by the sending app today,
/// but it arrives from an unauthenticated peer over an open Nearby link — so it
/// is attacker-controlled input being used to build a filesystem path. A name of
/// `../../databases/app.db` would otherwise write straight through the sandbox.
///
/// Takes the last path segment, keeps only `[A-Za-z0-9._-]`, refuses a
/// leading dot (a hidden file, and `..` in particular), and falls back to a
/// generated name when nothing usable survives.
String sanitiseMeshFileName(String raw, {String fallbackExt = 'bin'}) {
  // Split on both separators: an Android peer sends `/`, a tampered one may
  // send `\`, and `p.basename` only honours the host platform's.
  final lastSep = max(raw.lastIndexOf('/'), raw.lastIndexOf('\\'));
  var name = lastSep >= 0 ? raw.substring(lastSep + 1) : raw;

  name = name.replaceAll(RegExp(r'[^A-Za-z0-9._-]'), '_');
  while (name.startsWith('.')) {
    name = name.substring(1);
  }
  if (name.length > kMaxMeshFileNameChars) {
    // Trim the stem, never the extension — the extension is what decides which
    // app `open_filex` hands the file to.
    final dot = name.lastIndexOf('.');
    final ext = (dot > 0 && name.length - dot <= 6) ? name.substring(dot) : '';
    name = name.substring(0, kMaxMeshFileNameChars - ext.length) + ext;
  }
  if (name.isEmpty) {
    name = '${DateTime.now().millisecondsSinceEpoch}_mesh.$fallbackExt';
  }
  return name;
}

/// Whether a pending mesh message is still waiting on an upload and must not be
/// reconciled to Firestore yet.
///
/// The readiness signal differs by type, which is why this is a function and not
/// an inline `mediaUrl == null`. Images, voice notes and video upload in the
/// clear and are ready once they have a URL; a **document is encrypted**, so the
/// thing that proves the upload landed is its [MediaKeyBundle], not a URL — a
/// document reconciled without one is a bubble the receiver can never open.
///
/// Returning `true` keeps the message pending for the next reconnect rather than
/// committing something broken and dropping the local copy for good.
bool meshMessageNeedsUpload(
  MessageType type, {
  String? localFilePath,
  String? mediaUrl,
  Map<String, dynamic>? mediaKey,
}) {
  if (localFilePath == null) return false;
  return switch (type) {
    MessageType.image ||
    MessageType.audio ||
    MessageType.video =>
      mediaUrl == null,
    MessageType.document => mediaKey == null || mediaKey.isEmpty,
    _ => false,
  };
}
